import sympy as sp
import time

def generate_polar_kinematics():
    print("Deriving von Karman kinematics for arbitrary isoparametric elements...")
    t0 = time.time()
    
    ux, uy = sp.symbols('ux uy', real=True)
    vx, vy = sp.symbols('vx vy', real=True)
    wx, wy = sp.symbols('wx wy', real=True)
    thx_x, thx_y = sp.symbols('thx_x thx_y', real=True)
    thy_x, thy_y = sp.symbols('thy_x thy_y', real=True)
    thx, thy = sp.symbols('thx thy', real=True)
    
    kinematics = sp.Matrix([ux, uy, vx, vy, wx, wy, thx_x, thx_y, thy_x, thy_y, thx, thy])
    E, nu, t = sp.symbols('E nu t', real=True, positive=True)
    
    # Nonlinear von Karman Strains
    eps_m = sp.Matrix([ux + 0.5 * wx**2, vy + 0.5 * wy**2, uy + vx + wx * wy])
    eps_b = sp.Matrix([thy_x, -thx_y, thy_y - thx_x])
    eps_s = sp.Matrix([wx + thy, wy - thx])
    
    # Constitutive Matrices
    factor_m = E * t / (1 - nu**2)
    D_m = factor_m * sp.Matrix([[1, nu, 0], [nu, 1, 0], [0, 0, (1-nu)/2]])
    
    factor_b = E * t**3 / (12 * (1 - nu**2))
    D_b = factor_b * sp.Matrix([[1, nu, 0], [nu, 1, 0], [0, 0, (1-nu)/2]])
    
    factor_s = (5.0/6.0) * E * t / (2 * (1 + nu))
    D_s = factor_s * sp.Matrix([[1, 0], [0, 1]])
    
    # Strain Energy Density
    W = 0.5 * (eps_m.T * D_m * eps_m + eps_b.T * D_b * eps_b + eps_s.T * D_s * eps_s)[0]
    
    # Derivatives
    dW_dkin = sp.Matrix([sp.diff(W, var) for var in kinematics])
    d2W_dkin2 = dW_dkin.jacobian(kinematics)
    
    # Maximum Principal Strain (with 1e-15 stabilizer to prevent NaN division-by-zero)
    eps_x, eps_y, gam_xy = eps_m[0], eps_m[1], eps_m[2]
    eps_principal = (eps_x + eps_y)/2 + sp.sqrt(((eps_x - eps_y)/2)**2 + (gam_xy/2)**2 + 1e-15)
    deps_dkin = sp.Matrix([sp.diff(eps_principal, var) for var in kinematics])

    print(f"Derivations complete in {time.time() - t0:.2f} seconds. Generating Numba kernel...")
    
    with open("polar_kinematics.py", "w") as f:
        f.write("# AUTO-GENERATED BY SYMPY\n")
        f.write("import numpy as np\n")
        f.write("import math\n")
        f.write("from numba import njit\n\n")
        
        f.write("@njit(cache=True)\n")
        f.write("def evaluate_gauss_point(kin_vec, E, nu, t):\n")
        f.write("    ux, uy, vx, vy, wx, wy, thx_x, thx_y, thy_x, thy_y, thx, thy = kin_vec\n")
        
        f.write("    dW = np.zeros(12)\n")
        for i in range(12):
            if dW_dkin[i] != 0: f.write(f"    dW[{i}] = {sp.pycode(dW_dkin[i])}\n")
                
        f.write("    d2W = np.zeros((12, 12))\n")
        for i in range(12):
            for j in range(12):
                if d2W_dkin2[i,j] != 0: f.write(f"    d2W[{i},{j}] = {sp.pycode(d2W_dkin2[i,j])}\n")
                    
        f.write(f"    eps_p = {sp.pycode(eps_principal)}\n")
        
        f.write("    deps = np.zeros(12)\n")
        for i in range(12):
            if deps_dkin[i] != 0: f.write(f"    deps[{i}] = {sp.pycode(deps_dkin[i])}\n")
                
        f.write("    return dW, d2W, eps_p, deps\n")

if __name__ == "__main__":
    generate_polar_kinematics()